name: ${APP_NAME:-scaffold}

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database:/var/lib/mysql
    networks:
      - default
###< doctrine/doctrine-bundle ###

  caddy:
    image: caddy:2.9.1-alpine
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./:/app:cached
      - ./config/docker/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default

  php:
    build:
      context: .
      target: app-dev
    working_dir: /app
    volumes:
      - ./:/app:cached
      - ./config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-custom.ini
    depends_on:
      - database
    networks:
      - default

networks:
  default:

volumes:
  database:
  caddy_data:
  caddy_config: