name: ${APP_NAME:-scaffold}

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ../database:/var/lib/mysql
    networks:
      - default
###< doctrine/doctrine-bundle ###

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes:
      - ./:/app:cached
      - ./config/docker/nginx:/etc/nginx/conf.d
    networks:
      - default

  php:
    build: .
    working_dir: /app
    volumes:
      - ./:/app:cached
      - ./config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-custom.ini
    depends_on:
      - database
    networks:
      - default

networks:
  default:
