name: ${APP_NAME}_prod

services:
  caddy:
    restart: unless-stopped
    image: ${CI_REGISTRY_IMAGE}:caddy-${RELEASE}
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - app_public_storage:/app/public/uploads

  php:
    restart: unless-stopped
    image: ${CI_REGISTRY_IMAGE}:app-${RELEASE}
    volumes:
      - app_public_storage:/app/public/uploads
      - app_private_storage:/app/storage

volumes:
  caddy_data:
  caddy_config:
  app_public_storage:
  app_private_storage:
