name: ${APP_NAME}_prod

services:
  caddy:
    restart: unless-stopped
    image: ${CI_REGISTRY_IMAGE}:caddy-${RELEASE}
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  php:
    restart: unless-stopped
    image: ${CI_REGISTRY_IMAGE}:app-${RELEASE}

volumes:
  caddy_data:
  caddy_config:
